apiVersion: v1
kind: ConfigMap
metadata:
  name: yangfan-grafana-config
  namespace: yangfan
data:
  grafana.ini: |
    [provisioning]
    enabled = true
    directory = /etc/grafana/provisioning
    
    [datasource.prometheus]
    type = prometheus
    url = http://yangfan-prometheus:9090
    access = proxy
    
    [dashboard]
    enabled = true
    default_home_dashboard_path = /etc/grafana/provisioning/yangfan-for-distributed-load-testing.json
    kiosk = false
    
    [dashboard.providers.yangfan-for-distributed-load-testing]
    enabled = true
    provider = file
    path = /etc/grafana/provisioning/yangfan-for-distributed-load-testing.json
    
    [dashboard.providers.yangfan-for-node-status.json]
    enabled = true
    provider = file
    path = /etc/grafana/provisioning/yangfan-for-node-status.json


