version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  server:
    build:
      context: ../../
      dockerfile: ./server/Dockerfile
    container_name: yangfan-server
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml
    ports:
      - '8888:8888'
      - '7967:7967'
    networks:
      network:
        ipv4_address: 177.7.0.12

  web:
    build:
      context: ../../
      dockerfile: ./web/Dockerfile
    container_name: yangfan-web
    restart: always
    ports:
      - '8080:8080'
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  master:
    build:
      context: ../../
      dockerfile: ./master/Dockerfile
    container_name: yangfan-master
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml
    ports:
      - '7966:7966'
      - '9093:9093'
      - '9092:9092'
    networks:
      network:
        ipv4_address: 177.7.0.15

  work:
    build:
      context: ../../
      dockerfile: ./work/Dockerfile
    container_name: yangfan-work
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml
    networks:
      network:
        ipv4_address: 177.7.0.16

  timer:
    build:
      context: ../../
      dockerfile: ./timer/Dockerfile
    container_name: yangfan-timer
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml
    networks:
      network:
        ipv4_address: 177.7.0.13

  run:
    build:
      context: ../../
      dockerfile: ./run/Dockerfile
    container_name: yangfan-run
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml
    networks:
      network:
        ipv4_address: 177.7.0.18

  prometheus:
    image: prom/prometheus
    container_name: yangfan-prometheus
    hostname: yangfan-prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      network:
        ipv4_address: 177.7.0.201

  pushgateway:
    container_name: yangfan-pushgateway
    hostname: yangfan-pushgateway
    image: prom/pushgateway
    restart: always
    ports:
      - '9091:9091'
    networks:
      network:
        ipv4_address: 177.7.0.202

  grafana:
    container_name: yangfan-grafana
    image: "grafana/grafana:9.5.1"
    user: root
    ports:
      - '3000:3000'
    networks:
      network:
        ipv4_address: 177.7.0.203
    restart: always
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/log:/var/log/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PATHS_CONFIG=/etc/grafana/provisioning/grafana.ini
